<?php
/**
 * One Pica
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to codemaster@onepica.com so we can send you a copy immediately.
 * 
 * @category    PlanetPayment
 * @package     PlanetPayment_IpayGateway
 * @copyright   Copyright (c) 2012 Planet Payment Inc. (http://www.planetpayment.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Planet Payment
 *
 * @category   PlanetPayment
 * @package    PlanetPayment_IpayGateway
 * @author     One Pica Codemaster <codemaster@onepica.com>
 */
?>
<?php $_code = $this->getMethodCode() ?>
<div class="form-list" id="payment_form_<?php echo $_code ?>" style="display: none;">
    <?php if ($this->hasPaymentProfiles()) { ?>
        <label for="<?php echo $_code ?>_payment_profile_id"><?php echo $this->__('Store Credit Cards') ?></label>
        <div class="input-box" style="margin-bottom: 10px;">
            <?php echo $this->getPaymentProfileSelectHtml() ?>
        </div>
    <?php } ?>
    <?php $selectedProfile = $this->getSelectedProfile() ?>
    <ul<?php if ($this->hasPaymentProfiles() && $selectedProfile->getId()) { ?> style="display: none;"<?php } ?>>
        <li>
            <label for="<?php echo $_code ?>_cc_type"><?php echo $this->__('Credit Card Type') ?> <span>*</span></label>
            <div class="input-box">
                <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry validate-cc-type-select ipay-payment">
                    <option value=""><?php echo $this->__('--Please Select--') ?></option>
                    <?php $_ccType = $this->getInfoData('cc_type') ?>
                    <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                        <option value="<?php echo $_typeCode ?>"<?php if ($_typeCode == $_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </li>
        <li>
            <label for="<?php echo $_code ?>_cc_number"><?php echo $this->__('Credit Card Number') ?> <span class="required">*</span></label>
            <div class="input-box">
                <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type  ipay-payment" value="<?php echo $this->getInfoData('cc_number') ?>" />
            </div>
        </li>
        <li id="<?php echo $_code ?>_cc_type_exp_div">
            <label for="<?php echo $_code ?>_expiration"><?php echo $this->__('Expiration Date') ?> <span class="required">*</span></label>
            <div class="input-box">
                <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry ipay-payment">
                    <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                    <?php foreach ($this->getCcMonths() as $k => $v): ?>
                        <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry ipay-payment">
                    <?php foreach ($this->getCcYears() as $k => $v): ?>
                        <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </li>
        <?php echo $this->getChildHtml() ?>
        <?php if ($this->hasVerification()): ?>
            <li id="<?php echo $_code ?>_cc_type_cvv_div">
                <label for="<?php echo $_code ?>_cc_cid"><?php echo $this->__('Card Verification Number') ?> <span class="required">*</span></label>
                <div class="input-box">
                    <div class="v-fix">
                        <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn ipay-payment" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="<?php echo $this->getInfoData('cc_cid') ?>" />
                    </div>
                </div>
            </li>
        <?php endif; ?>
    </ul>	
    <input type="hidden" name="payment[is_visible]" value="<?php echo $this->isGuestCheckout() ? '0' : '1' ?>" />

    <div class="clearer"></div>
    <?php if ($this->hasPaymentProfiles()) { ?>
        <script type="text/javascript">
            //<![CDATA[
            var ipayPayment = new ipay.Payment(
            'payment_form_<?php echo $_code ?>',
            '<?php echo $_code ?>_payment_profile_id',
            'p_method_<?php echo $_code ?>',
            '<?php echo Mage::helper("adminhtml")->getUrl('ipayadmin/adminhtml_checkout/getIpayCurrencies'); ?>'
        );
            //]]>
        </script>
    <?php } ?>
    <div id="currency_selector"></div>
</div>