<?php
/**
 * One Pica
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to codemaster@onepica.com so we can send you a copy immediately.
 * 
 * @category    PlanetPayment
 * @package     PlanetPayment_IpayGateway
 * @copyright   Copyright (c) 2012 Planet Payment Inc. (http://www.planetpayment.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Planet Payment
 *
 * @category   PlanetPayment
 * @package    PlanetPayment_IpayGateway
 * @author     One Pica Codemaster <codemaster@onepica.com>
 */
/**
 * @see OnePica_IpayGateWay_Block_Info
 */
?>
<address>
    <?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?><br />
    <?php echo $this->__('Card Type: %s', $this->getCcTypeName()); ?><br />
    <?php echo $this->__('Card Number: XXXX-%s', $this->getInfo()->getCcLast4()); ?><br />
    <?php echo $this->__('Expiration: %s/%s', $this->getCcExpMonth(), $this->getInfo()->getCcExpYear()); ?><br />
    <?php echo $this->__('Ipay Profile ID: %s', $this->getInfo()->getIpayProfileId()); ?><br />
    <?php echo $this->__('Ipay Payment Currency: %s', $this->getInfo()->getIpayCurrencyCode()); ?>
</address>