<?php
/**
 * One Pica
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to codemaster@onepica.com so we can send you a copy immediately.
 * 
 * @category    PlanetPayment
 * @package     PlanetPayment_IpayGateway
 * @copyright   Copyright (c) 2012 Planet Payment Inc. (http://www.planetpayment.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Planet Payment
 *
 * @category   PlanetPayment
 * @package    PlanetPayment_IpayGateway
 * @author     One Pica Codemaster <codemaster@onepica.com>
 */
?>
<div class="page-title title-buttons">
    <h1><?php echo $this->__('Stored Credit Card Profiles') ?></h1>
    <button type="button" class="button" onclick="location.href='<?php echo $this->getAddUrl() ?>';" title="<?php echo $this->__('Add New Credit Card Profile') ?>"><span><span><?php echo $this->__('Add New Credit Card Profile') ?></span></span></button>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<ul>
    <?php $profiles = $this->getPaymentProfiles() ?>
    <?php if (count($profiles)): ?>
        <?php foreach ($profiles as $profile): ?>
            <li class="info-box">
                <dl>
                    <dt><?php echo $this->__('Name'); ?>:</dt>
                    <dd><?php echo $profile->getName(); ?></dd>
                    <?php if ($profile) { ?>
                        <dt><?php echo $this->__('Card Type'); ?>:</dt>
                        <dd><?php echo $profile->getCardTypeName(); ?></dd>
                        <dt><?php echo $this->__('Card Number'); ?>:</dt>
                        <dd><?php echo $this->__('Ends in') . ' ' . $profile->getCardNumberLast4(); ?></dd>
                    <?php } ?>
                    <dt><?php echo $this->__('Address'); ?>:</dt>
                    <dd><?php echo $profile->getAddress(); ?>, <?php echo $profile->getCity(); ?>, <?php echo $profile->getState(); ?> <?php echo $profile->getZip(); ?>, <?php echo $profile->getCountry(); ?></dd>
                    <dt><?php echo $this->__('Phone'); ?>:</dt>
                    <dd><?php echo $profile->getPhoneNumber(); ?></dd>
                </dl>
                <p class="actions">
                    <a style="margin-left: 0;" href="<?php echo $this->getEditUrl($profile) ?>"><?php echo $this->__('Edit') ?></a>
                    <a class="btn-blank" href="#" onclick="return deleteProfile('<?php echo $profile->getId() ?>');"><?php echo $this->__('Delete') ?></a>
                </p>
            </li>
        <?php endforeach; ?>
    <?php else: ?>
        <li class="item empty">
            <p><?php echo $this->__('You have no stored credit card profiles.') ?></p>
        </li>
    <?php endif ?>
</ul>
<script type="text/javascript">
    //<![CDATA[
    function deleteProfile (profileId) {
        if (confirm('<?php echo $this->__('Are you sure you want to delete this profile?') ?>')) {
            window.location='<?php echo $this->getDeleteUrl() ?>profile_id/' + profileId;
        }
        return false;
    }
    //]]>
</script>
<style type="text/css">
    .info-box { float: left; width: 44%; margin-right: 2%; }
    .info-box:nth-child(even) { float: right; margin-right: 0; }
    .info-box dl { margin: 10px 17px 17px; }
    .info-box dt { float: left; clear: left; width: 30%; margin-right: 5%; font-weight: bold; }
    .info-box dd { float: left; width: 65%; }
    p.actions { clear: both; padding: 10px 17px 17px; }
</style>